### ISSUE TITLE
Change coordinate system to North East Down (NED)

### ISSUE THREAD

**Issue by jorisquist** [LOBSTER-Robotics/LobsterSimulator#14]
The Pybullet uses the North East Up coordinate system, while the control software and the sensors use the NED coordinate system. To fix this, the simulator will need to use the NED coordinate system and the PybulletAPI wrapper in the simulator will need to deal with conversion between the two.

**Comment by gijskoning** [comment]
I am still not so sure if we should make this change. At least we should have conversion methods for both. Maybe we can have a meeting with Jelle and Danny?

Also it is ENU and NED not NEU and NED ;) https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates

**Comment by jorisquist** [comment]
> I am still not so sure if we should make this change. At least we should have conversion methods for both. Maybe we can have a meeting with Jelle and Danny?

Sure, I think I have the needed conversion method ready in #15, so you could look at that if you want.

> Also it is ENU and NED not NEU and NED ;) https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates

Yes, but actually no 😅. It's should have been North-West-Up so NWU.
