### ISSUE TITLE
Update DVL implementation

### ISSUE THREAD

**Issue by jorisquist** [LOBSTER-Robotics/LobsterSimulator#22]
The DVL now measures the altitude by measuring the distance from 100 meter depth, when it is known how the real DVL measures this the simulator DVL should be updated to work the same way.

![IMG_20200724_172742](https://user-images.githubusercontent.com/15105256/88408169-77355980-cdd3-11ea-9bad-dc68886a1b7f.jpg)

**Comment by gijskoning** [comment]
Is this one done now?

**Comment by jorisquist** [comment]
Yes
